import React from 'react';
import type { SignatureData } from '../../types/signature';

interface TemplateProps {
    data: SignatureData;
    logoSrc: string;
}

/**
 * Template 16: Developer Code
 * Features: Terminal-like appearance, monospace font, syntax highlighting colors
 */
export const Template16: React.FC<TemplateProps> = ({ data, logoSrc }) => {

    // Custom syntax colors based on One Dark theme
    const colors = {
        keyword: '#c678dd', // purple
        prop: '#e06c75',    // red
        string: '#98c379',  // green
        link: '#61afef',    // blue
        text: '#abb2bf',    // gray
        bg: '#282c34'       // dark
    };

    return (
        <div style={{
            fontFamily: '"Courier New", Courier, monospace',
            fontSize: '13px',
            lineHeight: '1.5',
            backgroundColor: colors.bg,
            color: colors.text,
            padding: '16px',
            borderRadius: '8px',
            display: 'inline-block',
            minWidth: '320px'
        }}>
            <table cellPadding="0" cellSpacing="0" border={0} width="100%">
                <tbody>
                    <tr>
                        {/* Can optionally include avatar, but pure code is cooler. Let's add avatar as a comment header or alongside. 
                Let's put avatar on right side floating */}
                        <td valign="top">
                            <div><span style={{ color: colors.keyword }}>const</span> <span style={{ color: '#e5c07b' }}>me</span> <span style={{ color: colors.keyword }}>=</span> {'{'}</div>

                            <div style={{ paddingLeft: '24px' }}>
                                <div>
                                    <span style={{ color: colors.prop }}>name</span>: <span style={{ color: colors.string }}>"{data.fullName}"</span>,
                                </div>
                                <div>
                                    <span style={{ color: colors.prop }}>title</span>: <span style={{ color: colors.string }}>"{data.title}"</span>,
                                </div>

                                {data.company && (
                                    <div>
                                        <span style={{ color: colors.prop }}>company</span>: <span style={{ color: colors.string }}>"{data.company}"</span>,
                                    </div>
                                )}

                                <div>
                                    <span style={{ color: colors.prop }}>contact</span>: {'{'}
                                </div>

                                <div style={{ paddingLeft: '24px' }}>
                                    {data.email && (
                                        <div>
                                            email: <a href={`mailto:${data.email}`} style={{ color: colors.link, textDecoration: 'none' }}>"{data.email}"</a>,
                                        </div>
                                    )}
                                    {data.website && (
                                        <div>
                                            web: <a href={data.website.startsWith('http') ? data.website : `https://${data.website}`} style={{ color: colors.link, textDecoration: 'none' }}>"{data.website.replace(/^https?:\/\//, '')}"</a>,
                                        </div>
                                    )}
                                    {data.socialLinks.twitter && (
                                        <div>
                                            x: <a href={data.socialLinks.twitter} style={{ color: colors.link, textDecoration: 'none' }}>"@{data.socialLinks.twitter.split('/').pop()}"</a>,
                                        </div>
                                    )}
                                </div>
                                <div>{'}'},</div>
                            </div>
                            <div>{'}'};</div>

                            <div style={{ marginTop: '10px', color: '#5c6370', fontStyle: 'italic' }}>
                    // Generated by SignatureOS
                            </div>
                        </td>

                        {/* Avatar Column (Optional) */}
                        <td valign="top" align="right" style={{ paddingLeft: '16px' }}>
                            <img
                                src={logoSrc}
                                alt="avatar"
                                width="80"
                                height="80"
                                style={{
                                    borderRadius: '8px',
                                    border: '2px solid #3e4451',
                                    display: 'block',
                                    objectFit: 'cover'
                                }}
                            />
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    );
};
